#pragma once
#include <raylib.h>
#define RAYGUI_IMPLEMENTATION
#include <raygui.h>
#define GUI_START_MENU_IMPLEMENTATION
#include "gui_Start_Menu.h"
#include <iostream>
#include <amber.h>
#include <string>
#include <thread>
#include <chrono>
#include "jethro.h"
#include "tileset.h"
#include "game.h"